# Failure of sending

fun goAlright() {
  var ap = new(); # Yay synchronisation!
  try {
    var s = fork (fun (s) {
  #    cancel(s);
      ignore(request(ap));
      ignore(receive(s));
    });
    ignore(accept(ap));
    ignore(send(5, s))
  } as (_) in {
    print("send successful")
  } otherwise {
    print("an exception occurred!")
  }
}


fun goBadly() {
  var ap = new(); # Yay synchronisation!
  try {
    var s = fork (fun (s) {
      ignore(request(ap));
      cancel(s);
    });
    ignore(accept(ap));
    ignore(send(5, s))
  } as (_) in {
    print("send successful")
  } otherwise {
    print("an exception occurred!")
  }
}


goBadly()
#goAlright()
